language: php

php:
  - 5.4
  - 5.5

before_script:
    - git clone -q https://github.com/phalcon/cphalcon.git
    - (cd cphalcon/build/32bits; export CFLAGS="-g3 -O1 -fno-delete-null-pointer-checks"; phpize && ./configure --enable-phalcon && make -j2 && sudo make install && phpenv config-add ../../../tests/phalcon.ini)
    - wget http://getcomposer.org/composer.phar
    - php composer.phar install

script:
    - mkdir -p build/logs
    - bin/phpunit -c phpunit.xml.dist

after_script:
    - bin/phpcs -v --report=summary --standard=PSR1,PSR2 src/ tests/
    - php bin/coveralls -v
