language: php

php:
  - 5.4
  - 5.5

before_script:
    - wget http://getcomposer.org/composer.phar
    - php composer.phar install
    - git clone -q https://github.com/phalcon/cphalcon.git
    - (CWD=$(pwd); cd cphalcon/build; ./install; echo "extension = phalcon.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; cd $CWD)

script:
    - mkdir -p build/logs
    - bin/phpunit -c phpunit.xml.dist

after_script:
    - bin/phpcs -v --report=summary --standard=PSR1,PSR2 src/ tests/
    - php bin/coveralls -v
